version: 1
formatters:
  simple:
    format: '%(name)s / %(message)s'
  precise:
    format: '%(asctime)s / %(name)s / %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stderr
  sizerotate:
    class : logging.handlers.RotatingFileHandler
    formatter: precise
    filename: earthporn.log
    maxBytes: 4194304
    backupCount: 3
    encoding: UTF-8
  timerotate:
    class : logging.handlers.TimedRotatingFileHandler
    formatter: precise
    filename: earthporn.log
    when: D
    interval: 1
    backupCount: 7
    encoding: UTF-8
loggers:
  earthporn:
    level: DEBUG
    handlers: [console,timerotate]
    propagate: no
  requests.packages.urllib3:
    level: DEBUG
    handlers: [console,timerotate]
    propagate: no
root:
  level: DEBUG
  handlers: [console,timerotate]
